apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
        - image: us.icr.io/sn-labs-majorgowan/dealership:latest
          imagePullPolicy: Always
          name: dealership
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: backend_url
              value: "https://majorgowan-3030.theiadockernext-0-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai"
            - name: sentiment_analyzer_url
              value: "https://sentianalyzer.26c7u321p7ko.us-south.codeengine.appdomain.cloud/"
      restartPolicy: Always